/**
 * signs — picks which dataset clip the avatar plays.
 *
 * SIGN_LIBRARY (generated by scripts/extract_vrm_poses.py) holds ~100 real
 * Isharah-Selfi clips, each with its Arabic sentence, an English translation
 * and a topic (greeting, medical, emergency, education, kids, banking, legal,
 * travel).  Pages ask for a topic playlist; the Text→Sign box asks for the
 * best match to whatever was typed.
 */
import { SIGN_LIBRARY } from './signLibrary'

export const ALL_SIGNS = Object.keys(SIGN_LIBRARY)

/** ids of a topic, in library order (falls back to every sign) */
export function signsFor(topic, count) {
  const ids = ALL_SIGNS.filter((id) => SIGN_LIBRARY[id].topic === topic)
  const list = ids.length ? ids : ALL_SIGNS
  return count ? list.slice(0, count) : list
}

/** the dataset sentence a clip signs, in the UI language */
export function signText(id, lang) {
  const e = SIGN_LIBRARY[id]
  return e ? (lang === 'ar' ? e.ar : e.en) : ''
}

function hash(str) {
  let h = 2166136261
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619) }
  return h >>> 0
}

/** stable pseudo-random pick — the same seed always gives the same sign */
export function pickSign(seed, topic) {
  const list = signsFor(topic)
  return list[hash(String(seed)) % list.length]
}

/** e.g. 3 different signs from a topic, starting at a seed-dependent offset */
export function pickSigns(seed, topic, count) {
  const list = signsFor(topic)
  const start = hash(String(seed)) % list.length
  return Array.from({ length: Math.min(count, list.length) }, (_, i) => list[(start + i) % list.length])
}

/* ------------------------------ text → sign ------------------------------ */

const STOP = new Set((
  'the a an is are am was were be i me my we our you your he she it they to of and or for in on at do does did can could would ' +
  'please want need like with this that there here what where when how who from by as not no yes ' +
  'من في على الى عن ما هل هذا هذه هو هي انا انت نحن ان لا و او يا كم اين متي كيف'
).split(/\s+/))

const norm = (s) =>
  String(s || '')
    .toLowerCase()
    .replace(/[ً-ٰٟ]/g, '')          // diacritics
    .replace(/[إأآ]/g, 'ا').replace(/ة/g, 'ه').replace(/ى/g, 'ي')
    .replace(/[^\p{L}\p{N}\s]/gu, ' ')

const tokens = (s) =>
  norm(s).split(/\s+/).filter(Boolean)
    .map((w) => (w.length > 3 && w.startsWith('ال') ? w.slice(2) : w))
    .filter((w) => w.length > 1 && !STOP.has(w))

const stem = (w) => (w.length > 4 ? w.replace(/(ing|ed|es|s)$/, '') : w)

const INDEX = ALL_SIGNS.map((id) => {
  const e = SIGN_LIBRARY[id]
  return {
    id,
    topic: e.topic,
    main: new Set([...tokens(e.en), ...tokens(e.ar)].map(stem)),
    kw: new Set(tokens(e.kw).map(stem)),
  }
})

/**
 * Best clip for a piece of text.  Word overlap with the clip's sentence /
 * keywords; a hint topic breaks ties.  With no overlap at all it returns a
 * stable "random" sign from the hint topic, since sign language reads the
 * same whatever the sentence.
 */
export function matchSign(text, topic) {
  const q = tokens(text).map(stem)
  let best = null
  let bestScore = 0
  for (const e of INDEX) {
    let s = 0
    for (const w of q) {
      if (e.main.has(w)) s += 1
      else if (e.kw.has(w)) s += 0.6
      else if (w.length > 4 && [...e.main].some((m) => m.length > 4 && (m.startsWith(w) || w.startsWith(m)))) s += 0.5
    }
    if (s > 0 && topic && e.topic === topic) s *= 1.25
    if (s > bestScore) { best = e.id; bestScore = s }
  }
  return best || pickSign(norm(text).trim() || 'sign', topic)
}

/** one clip per clause ("Hello. I need a painkiller." → 2 signs), max 4 */
export function signsForText(text, topic) {
  const clauses = String(text || '').split(/[.!?؟،,;\n]+/).map((c) => c.trim()).filter(Boolean)
  const out = []
  for (const c of (clauses.length ? clauses : [text || ''])) {
    const id = matchSign(c, topic)
    if (!out.length || out[out.length - 1] !== id) out.push(id)
    if (out.length === 4) break
  }
  return out
}
