export const APP_NAME = { ar: 'الطبي', en: 'Medical' }

const BODY_ZONE_LABELS = {
  ar: { head: 'الرأس', chest: 'الصدر', abdomen: 'البطن', armL: 'الذراع اليسرى', armR: 'الذراع اليمنى', legL: 'الساق اليسرى', legR: 'الساق اليمنى' },
  en: { head: 'Head', chest: 'Chest', abdomen: 'Abdomen', armL: 'Left arm', armR: 'Right arm', legL: 'Left leg', legR: 'Right leg' },
}

// Richer per-patient records so the queue can open into a real case-detail
// sheet (vitals, triage reasoning, transcript) instead of a flat row.
const QUEUE_CASES = {
  ar: [
    {
      id: 'A-214', complaint: 'ألم في الصدر وضيق تنفس', triage: 'urgent', wait: '4 د',
      vitals: { hr: 118, spo2: 91, bp: '148/94' },
      zone: 'الصدر',
      transcript: 'أشعر بألم حاد في الصدر وضيق في التنفس منذ نصف ساعة.',
      reasoning: 'ألم صدر حاد مصحوب بانخفاض تشبع الأكسجين وارتفاع ضغط الدم — أولوية عالية لاستبعاد حالة قلبية.',
    },
    {
      id: 'A-215', complaint: 'كسر مشتبه به في المعصم', triage: 'moderate', wait: '12 د',
      vitals: { hr: 88, spo2: 98, bp: '122/80' },
      zone: 'الذراع اليمنى',
      transcript: 'سقطت على يدي وأشعر بألم شديد وتورم في معصمي الأيمن.',
      reasoning: 'إصابة طرفية مع تورم واضح، العلامات الحيوية مستقرة — أولوية متوسطة لتصوير أشعة.',
    },
    {
      id: 'A-216', complaint: 'حمى مرتفعة وصداع شديد', triage: 'urgent', wait: '6 د',
      vitals: { hr: 104, spo2: 96, bp: '110/72' },
      zone: 'الرأس',
      transcript: 'درجة حرارتي مرتفعة جدًا منذ الصباح ورأسي يؤلمني بشدة مع دوخة.',
      reasoning: 'حمى شديدة مع صداع حاد — يستدعي تقييمًا عاجلاً لاستبعاد عدوى خطيرة.',
    },
    {
      id: 'A-217', complaint: 'جرح سطحي يحتاج تنظيف وضماد', triage: 'nonUrgent', wait: '25 د',
      vitals: { hr: 76, spo2: 99, bp: '118/76' },
      zone: 'الذراع اليسرى',
      transcript: 'جرحت يدي اليسرى بسكين أثناء الطبخ، النزيف توقف لكن أحتاج تنظيفًا.',
      reasoning: 'جرح سطحي بسيط، لا نزيف نشط، العلامات الحيوية طبيعية — يمكن الانتظار بأمان.',
    },
    {
      id: 'A-218', complaint: 'ألم بطن متكرر منذ يومين', triage: 'moderate', wait: '18 د',
      vitals: { hr: 92, spo2: 97, bp: '126/82' },
      zone: 'البطن',
      transcript: 'أعاني من ألم متكرر في بطني منذ يومين، يزداد بعد الأكل.',
      reasoning: 'ألم بطني مستمر دون علامات إنذار حادة — أولوية متوسطة للتقييم.',
    },
    {
      id: 'A-219', complaint: 'فحص دوري بعد جراحة سابقة', triage: 'nonUrgent', wait: '32 د',
      vitals: { hr: 70, spo2: 99, bp: '114/74' },
      zone: 'البطن',
      transcript: 'أتيت لفحص متابعة روتيني بعد عمليتي الجراحية الأسبوع الماضي.',
      reasoning: 'زيارة متابعة روتينية، لا أعراض حادة — يمكن جدولتها ضمن قائمة الانتظار العادية.',
    },
  ],
  en: [
    {
      id: 'A-214', complaint: 'Chest pain, shortness of breath', triage: 'urgent', wait: '4 min',
      vitals: { hr: 118, spo2: 91, bp: '148/94' },
      zone: 'Chest',
      transcript: 'I have sharp chest pain and shortness of breath for the last half hour.',
      reasoning: 'Acute chest pain with low oxygen saturation and elevated blood pressure — high priority to rule out cardiac event.',
    },
    {
      id: 'A-215', complaint: 'Suspected wrist fracture', triage: 'moderate', wait: '12 min',
      vitals: { hr: 88, spo2: 98, bp: '122/80' },
      zone: 'Right arm',
      transcript: 'I fell on my hand, my right wrist is swollen and very painful.',
      reasoning: 'Peripheral injury with visible swelling, vitals stable — moderate priority for imaging.',
    },
    {
      id: 'A-216', complaint: 'High fever, severe headache', triage: 'urgent', wait: '6 min',
      vitals: { hr: 104, spo2: 96, bp: '110/72' },
      zone: 'Head',
      transcript: 'My temperature has been very high since this morning and my head hurts badly, I feel dizzy.',
      reasoning: 'High fever with severe headache — requires urgent evaluation to rule out serious infection.',
    },
    {
      id: 'A-217', complaint: 'Superficial wound, needs cleaning', triage: 'nonUrgent', wait: '25 min',
      vitals: { hr: 76, spo2: 99, bp: '118/76' },
      zone: 'Left arm',
      transcript: 'I cut my left hand with a knife while cooking, bleeding has stopped but it needs cleaning.',
      reasoning: 'Minor superficial wound, no active bleeding, normal vitals — safe to wait.',
    },
    {
      id: 'A-218', complaint: 'Recurring abdominal pain, 2 days', triage: 'moderate', wait: '18 min',
      vitals: { hr: 92, spo2: 97, bp: '126/82' },
      zone: 'Abdomen',
      transcript: 'I’ve had recurring abdominal pain for two days, it gets worse after eating.',
      reasoning: 'Persistent abdominal pain without acute red flags — moderate priority for evaluation.',
    },
    {
      id: 'A-219', complaint: 'Routine post-op check-up', triage: 'nonUrgent', wait: '32 min',
      vitals: { hr: 70, spo2: 99, bp: '114/74' },
      zone: 'Abdomen',
      transcript: 'I’m here for a routine follow-up after my surgery last week.',
      reasoning: 'Routine follow-up visit, no acute symptoms — can be scheduled within normal queue.',
    },
  ],
}

export const CONTENT = {
  ar: {
    home: {
      eyebrow: 'كشك الطوارئ · SignWorld',
      title: 'لا صمت في الطوارئ',
      subtitle: 'يحوّل الرمز الرقمي إشارة المريض إلى نص فوري للطاقم الطبي، ويوقّع رد الطبيب مباشرة أمام المريض.',
      patient: { title: 'دخول المريض', sub: 'صف حالتك بلغة الإشارة' },
      clinician: { title: 'دخول الطاقم الطبي', sub: 'استقبل واستجب للحالات' },
      stat: 'أكثر من 40 كشكًا موصولًا في أقسام الطوارئ',
      status: { label: 'النظام متصل', node: 'كشك #03 · طوارئ' },
    },
    checkin: {
      back: 'رجوع',
      title: 'تسجيل الدخول',
      subject: 'الخطوة 1 من 4',
      idLabel: 'رقم الملف',
      idValue: 'يُنشأ تلقائيًا عند الوصول',
      deptLabel: 'القسم',
      dept: 'الطوارئ — مستشفى الملك فهد',
      timeLabel: 'وقت الوصول',
      nextBtn: 'متابعة إلى العلامات الحيوية',
    },
    vitals: {
      back: 'رجوع',
      title: 'العلامات الحيوية',
      subject: 'الخطوة 2 من 4',
      hr: 'معدل النبض', spo2: 'الأكسجين', bp: 'ضغط الدم',
      note: 'تُقاس العلامات الحيوية تلقائيًا عبر جهاز الكشك.',
      nextBtn: 'متابعة إلى وصف الأعراض',
    },
    symptom: {
      back: 'رجوع',
      title: 'صف الأعراض',
      subject: 'الخطوة 3 من 4',
      mapHint: 'اضغط على مكان الألم',
      askBtn: 'التقط إشارة المريض',
      hideBtn: 'إخفاء الكاميرا',
      patientLabel: 'إشارة المريض',
      patientResult: 'أشعر بألم حاد في الصدر وضيق في التنفس منذ نصف ساعة.',
      nextBtn: 'متابعة إلى التصنيف',
    },
    triageResult: {
      back: 'رجوع',
      title: 'نتيجة التصنيف',
      subject: 'الخطوة 4 من 4',
      levelUrgent: 'عاجل', levelModerate: 'متوسط', levelNonUrgent: 'غير عاجل',
      bodyUrgent: 'تشير الأعراض والعلامات الحيوية إلى حالة تستدعي تقييمًا طبيًا فوريًا.',
      bodyModerate: 'حالتك تحتاج إلى تقييم طبي خلال وقت قصير.',
      bodyNonUrgent: 'حالتك مستقرة، سيتم استدعاؤك في دورك ضمن قائمة الانتظار.',
      clinicianLabel: 'رد الطاقم الطبي',
      captions: [
        'تم استلام بياناتك، سيتم استدعاؤك قريبًا.',
        'سيتم استدعاؤك خلال دقائق، الرجاء الانتظار هنا.',
      ],
      endBtn: 'إرسال إلى قائمة الانتظار',
    },
    queue: {
      back: 'رجوع',
      title: 'قائمة الانتظار',
      sub: 'الحالات الحالية في قسم الطوارئ',
      waitLabel: 'الانتظار',
      items: QUEUE_CASES.ar,
    },
    caseDetail: {
      vitalsLabel: 'العلامات الحيوية',
      zoneLabel: 'موضع الألم',
      transcriptLabel: 'نص الإشارة',
      reasoningLabel: 'سبب التصنيف',
      triageLabel: 'الأولوية',
      closeBtn: 'إغلاق',
      respondBtn: 'الرد بالإشارة',
      hr: 'النبض', spo2: 'الأكسجين', bp: 'الضغط',
    },
    settings: {
      back: 'رجوع',
      title: 'الإعدادات',
      deptLabel: 'القسم / الكشك',
      dept: 'الطوارئ — مستشفى الملك فهد',
      avatarLabel: 'مظهر المترجم الرقمي',
      avatars: ['سريري', 'ودود', 'رسمي'],
      langLabel: 'اللغة',
      integration: 'متصل بمنصة صحة',
    },
    nav: { live: 'الاستقبال', queue: 'الانتظار', settings: 'الإعدادات' },
    triage: { urgent: 'عاجل', moderate: 'متوسط', nonUrgent: 'غير عاجل' },
    bodyZones: BODY_ZONE_LABELS.ar,
  },
  en: {
    home: {
      eyebrow: 'ER Kiosk · SignWorld',
      title: 'No silence in the ER',
      subtitle: 'The Brain turns a patient’s signing into an instant transcript for staff, and signs the clinician’s reply back live.',
      patient: { title: 'Patient sign-in', sub: 'Describe your condition in sign' },
      clinician: { title: 'Clinician sign-in', sub: 'Receive and respond to cases' },
      stat: 'Over 40 kiosks connected across ER departments',
      status: { label: 'System online', node: 'Kiosk #03 · Emergency' },
    },
    checkin: {
      back: 'Back',
      title: 'Check-in',
      subject: 'Step 1 of 4',
      idLabel: 'Case ID',
      idValue: 'Auto-assigned on arrival',
      deptLabel: 'Department',
      dept: 'Emergency — King Fahd Hospital',
      timeLabel: 'Arrival time',
      nextBtn: 'Continue to vitals',
    },
    vitals: {
      back: 'Back',
      title: 'Vital Signs',
      subject: 'Step 2 of 4',
      hr: 'Heart rate', spo2: 'SpO2', bp: 'Blood pressure',
      note: 'Vitals are captured automatically by the kiosk sensor.',
      nextBtn: 'Continue to symptoms',
    },
    symptom: {
      back: 'Back',
      title: 'Describe Symptoms',
      subject: 'Step 3 of 4',
      mapHint: 'Tap where it hurts',
      askBtn: 'Capture patient signing',
      hideBtn: 'Hide camera',
      patientLabel: 'Patient signing',
      patientResult: 'I have sharp chest pain and shortness of breath for the last half hour.',
      nextBtn: 'Continue to triage',
    },
    triageResult: {
      back: 'Back',
      title: 'Triage Result',
      subject: 'Step 4 of 4',
      levelUrgent: 'Urgent', levelModerate: 'Moderate', levelNonUrgent: 'Non-urgent',
      bodyUrgent: 'Symptoms and vitals indicate a condition requiring immediate medical evaluation.',
      bodyModerate: 'Your condition needs medical evaluation within a short wait.',
      bodyNonUrgent: 'Your condition is stable — you’ll be called in your turn from the queue.',
      clinicianLabel: 'Clinician reply',
      captions: [
        'Your information has been received, you’ll be called shortly.',
        'You’ll be called in a few minutes, please wait here.',
      ],
      endBtn: 'Send to waiting queue',
    },
    queue: {
      back: 'Back',
      title: 'Waiting queue',
      sub: 'Current cases in the emergency department',
      waitLabel: 'Wait',
      items: QUEUE_CASES.en,
    },
    caseDetail: {
      vitalsLabel: 'Vital signs',
      zoneLabel: 'Symptom location',
      transcriptLabel: 'Signed transcript',
      reasoningLabel: 'Triage reasoning',
      triageLabel: 'Priority',
      closeBtn: 'Close',
      respondBtn: 'Reply in sign',
      hr: 'HR', spo2: 'SpO2', bp: 'BP',
    },
    settings: {
      back: 'Back',
      title: 'Settings',
      deptLabel: 'Department / kiosk',
      dept: 'Emergency — King Fahd Hospital',
      avatarLabel: 'Avatar style',
      avatars: ['Clinical', 'Friendly', 'Formal'],
      langLabel: 'Language',
      integration: 'Connected to Seha platform',
    },
    nav: { live: 'Intake', queue: 'Queue', settings: 'Settings' },
    triage: { urgent: 'Urgent', moderate: 'Moderate', nonUrgent: 'Non-urgent' },
    bodyZones: BODY_ZONE_LABELS.en,
  },
}
